parameters:
  database_driver: pdo_mysql
  database_host: localhost
  database_port: 3306
  database_name: viet-ipsum
  database_user: root
  database_password: root
  mailer_transport: smtp
  mailer_host: 127.0.0.1
  mailer_user: null
  mailer_password: null
  locale: en
  secret: b3b396db110844f11218a867fdab5822
  database_path: null
  node_path: /usr/local/bin/node
  node_modules_path: /usr/local/share/npm/lib/node_modules